### ISSUE TITLE
singleton-ops fails to compile on 2.12.5 nightly

### ISSUE THREAD

**Issue by SethTisue** [fthomas/singleton-ops#64]
on Scala 2.12.5-bin-64208ae at e.g. https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/2662/consoleFull:

```
[singleton-ops] [info] Compiling 46 Scala sources to /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.11/project-builds/singleton-ops-482ab9e7dc17ee2c6440b7fd6f23b2dafc452ee2/.jvm/target/scala-2.12/test-classes...
[singleton-ops] java.lang.StackOverflowError
[singleton-ops] 	at scala.reflect.internal.Types$TypeRef.equals(Types.scala:2152)
[singleton-ops] 	at scala.reflect.internal.util.Collections.sameElementsEquals(Collections.scala:69)
[singleton-ops] 	at scala.reflect.internal.util.Collections.sameElementsEquals$(Collections.scala:64)
[singleton-ops] 	at scala.reflect.internal.SymbolTable.sameElementsEquals(SymbolTable.scala:18)
[singleton-ops] 	at scala.reflect.internal.Types$TypeRef.equals(Types.scala:2152)
[singleton-ops] 	at scala.reflect.internal.util.Collections.sameElementsEquals(Collections.scala:69)
[singleton-ops] 	at scala.reflect.internal.util.Collections.sameElementsEquals$(Collections.scala:64)
[singleton-ops] 	at scala.reflect.internal.SymbolTable.sameElementsEquals(SymbolTable.scala:18)
[singleton-ops] 	at scala.reflect.internal.Types$TypeRef.equals(Types.scala:2152)
```

does this indicate a regression in Scala that we should fix before releasing 2.12.5...?

/cc @milessabin @soronpo

**Comment by SethTisue** [comment]
seeing the same error at e.g. https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/989/consoleFull on 2.13.0-pre-90ffe62-SNAPSHOT

**Comment by soronpo** [comment]
I'm checking the reason.

**Comment by SethTisue** [comment]
```
[info] Project singleton-ops---------------: SUCCESS (project rebuilt ok)
```

👍
